spring.application.name=4-22
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/4-22
spring.datasource.username=postgres
spring.datasource.password=postgres